### ISSUE TITLE
2022 data download status

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hakedataUSA#11]
@aaronmberger-nwfsc I pushed some commits this weekend that brought the repo up to speed. Hopefully it fixes the issues that you had last year where some files were not located in the appropriate place. Maybe we can schedule some virtual time today or tomorrow to go over things. I was able to successfully download the data but I haven't checked numbers. I will try to build the presentation today as an easy way to look at the data that is available.

**Comment by kellijohnson-NOAA** [comment]
Current status is Oracle is not working properly to check to see if the table for species information is available to @aaronmberger-nwfsc . 
In Oracle -- navigate to the PacFIN menu in upper left-hand corner. Toggle "Other Users". Then find "PACFIN_MARTS". In "Views" there should be "RPT_SPEX_FINAL_SPECIFICATION_DETAIL_V" this stores harvest guidelines. Try the following code
```
SELECT YEAR, FINAL_SPECIFICATION_DETAIL_ID,
  FISHERY_HARVEST_GUIDELINE, ACCEPTABLE_BIO_CATCH,
  ANNUAL_CATCH_LIMIT, TRAWL_METRIC_TONS,
  TRIBAL_SET_ASIDE, EFP_SET_ASIDE, RESEARCH_SET_ASIDE,
  OA_SET_ASIDE, BUFFER_SET_ASIDE, SET_ASIDE_TOTAL,
  SHOREBASED_IFQ, CATCHER_PROCESSOR, MOTHERSHIP
FROM
  PACFIN_MARTS.RPT_SPEX_FINAL_SPECIFICATION_DETAIL_V
WHERE
  ACL_CODE like 'PWHT' AND
  YEAR between 1980 and 2021
ORDER BY YEAR, FINAL_SPECIFICATION_DETAIL_ID
```
in the worksheet and click the play button. It should generate a table.

**Comment by aaronmberger-nwfsc** [comment]
I have resolved my Oracle software issue and the data pull ran for me with almost no errors.  A couple lingering errors exist, but I think those are relatively minor and are likely individual-user-based.

**Comment by aaronmberger-nwfsc** [comment]
It was further down in the README, pulldatabase() ran well.  I think most (if not all) of the errors were related to file structure and the inability to find specific files (like .csv's).  I will run it again and explicitly make notes, rather than doing quick fixes to get over those few hurdles.
