### ISSUE TITLE
Software for server

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hakedataUSA#14]
List of software to install on server
- ADMB-IDE (though I normally compile and install ADMB myself)
- Adobe acrobat pro
- Git
- Visual Studio Code (no admin rights needed)
- R
- rtools40
- Emacs (for Ian)

Need to ask for
-RStudio

Other software not requested but leaving here for reference.
- TinnR
- GitHub Desktop
- Google Earth
- SyncToy
- SyncBackFree
- GIMP

**Comment by aaronmberger-nwfsc** [comment]
If you want to install ADMB yourself, that is great and fine by me.  I don't need any of those other programs listed under my name - those were for my day to day laptop.  Although not needed per se, I would appreciate RStudio being installed just in case I don't make the transition to Visual Studio right away.

**Comment by kellijohnson-NOAA** [comment]
An IT request was submitted for the main software. I forgot to add RStudio but I will ask when I talk to them.

**Comment by kellijohnson-NOAA** [comment]
"leafcutter"
