### ISSUE TITLE
Research catch not updated in hake-assessment

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pacific-hake/hakedataUSA#20]
https://github.com/pacific-hake/hakedataUSA/blob/a7276fbe9225dbad2c54f98de290e1a5d881aff9/R/datatoassessment_catch.R#L11 is not picking up the research catch by month file, leading to it not being updated in [pacific-hake/data/us-research-catch-by-month.csv](https://github.com/pacific-hake/hake-assessment/blob/23c51163ab87e92cbbe2c8a709d3747ff03fb922/data/us-research-catch-by-month.csv) for the last three years.

**Comment by aaronmberger-nwfsc** [comment]
Good "catch" @kellijohnson-NOAA; it of course won't make much of a difference in the overall catch but nonetheless it is important to include.

**Comment by kellijohnson-NOAA** [comment]
Fixed somewhere along the lines.
